name: Build and Run

on:
  push:
    branches: [ "renewal-develop" ]
  pull_request:
    branches: [ "renewal-develop" ]
  workflow_dispatch:

env:
  XCODE_SELECT_PATH: '/Applications/Xcode_16.3.app/Contents/Developer'

jobs:
  build:
    runs-on: macos-15
    steps:
    - name: Set Xcode version
      run: sudo xcode-select -s '${{ env.XCODE_SELECT_PATH }}'
    - name: Show Swift version
      run: swift --version
    - name: Show Swift Package Manager version
      run: swift package --version
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run
      run: swift run -v
    - uses: actions/upload-artifact@v4
      with:
        path: Build/**
