name: Build and Run

on:
  push:
    branches: [ "renewal-develop" ]
  pull_request:
    branches: [ "renewal-develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Show Swift version
      run: swift --version
    - name: Show Swift Package Manager version
      run: swift package --version
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run
      run: swift run -v
    - uses: actions/upload-artifact@v4
      with:
        path: Build/**
